# EXERCICIO 1
# for ciclo in range(1,11):
#     print(f"peça nº {ciclo} processada com sucesso... :)")
# print("Ciclo de produção concluido... :)")

# Exercicio 2
# imagine a produção de frutas em uma feira. desejo apresentar as frutas banana, manga, abacaxi. com uma quantidade de 10 bananas, 5 mangas, 10 melancias e 13 abacaxi
# e no fim da produção gostaria de ter um total de produções

# print ("feira de frutas do Evaristo") 

# producao = {
#     "Banana": 10,
#     "Manga": 5,
#     "Melancia": 10,
#     "Abacaxi": 13
# }


# total_producao = sum(producao.values())


# for fruta, qtd in producao.items():
#     print(f"{fruta}: {qtd}")

# print(f"\nTotal da produção: {total_producao}")

# Exercicio 3
# montar ua tabuada inicialmente pode ser usado por um valor fixo e depois usar o programa em python


